INSERT INTO user_windows (id, proposed_answers)
VALUES
(0,'1'),
(0,'x + c'),
(0,'x'),
(1,'ax'),
(1,'a'),
(1,'a + c'),
(2,'x^{r+1} + c'),
(2,'x^r + c'),
(2,'\frac{x^{r+1}}{r} + c'),
(3,'c'),
(3,'x + c'),
(3,'\frac{-1}{x} + c'),
(4,'a^x + c'),
(4,'a^x lna + c'),
(4,'a^{x+1} + c'),
(5,'e^{x+1} + c'),
(5,'cosx'),
(5,'sinx'),
(6,'cosx + c'),
(6,'\frac{1}{sinx} + c'),
(6,'\frac{1}{cosx} + c'),
(7,'-sinx + c'),
(7,'cos^{-1}x'),
(7,'arcsinx'),
(8,'ctgx + c'),
(8,'\frac{1}{cosx} + c'),
(8,'\frac{1}{sinx} + c'),
(9,'-tgx + c'),
(9,'\frac{1}{sinx} + c'),
(9,'arcsinx'),
(10,'ln(x^2+1) + c'),
(10,'\frac{1}{x+1} + c'),
(10,'\frac{ln(x^2+1)}{x} + c'),
(11,'arccosx + c'),
(11,'arctgx + c'),
(11,'arcctgx + c'),
(12,'-\frac{1}{2} \int e^t dt'),
(12,'-lnt + c'),
(12,'\begin{vmatrix} t = lnx \\ dt = \frac{1}{x}dx  \end{vmatrix}'),
(12,'lnt + c'),
(12,'ln(lnx) + c'),
(13,'\begin{vmatrix} t = -x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}'),
(13,'-\int \frac{1}{t}dt'),
(13,'-lnt + c'),
(13,'-ln(cosx) + c'),
(13,'\begin{vmatrix} u = x   &  \frac{dv}{dx} = sinx \\ \frac{du}{dx} = 1  &   v = -cosx\end{vmatrix}'),
(14,'-\frac{1}{3} t^{\frac{3}{2}} + c'),
(14,'\begin{vmatrix} t = cosx \\ dt = -sinxdx \end{vmatrix}'),
(14,'\begin{vmatrix} t = lnx \\ dt = \frac{1}{x}dx  \end{vmatrix}'),
(14,'\int \frac{1}{t}dt'),
(14,'-xcosx + \int cosxdx'),
(15,'-\frac{1}{2}e^{-x^2} + c'),
(15,'\begin{vmatrix} t = a^2-x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}'),
(15,'-lnt + c'),
(15,'lnt + c'),
(15,'\begin{vmatrix} u = x   &  \frac{dv}{dx} = sinx \\ \frac{du}{dx} = 1  &   v = -cosx\end{vmatrix}'),
(16,'\begin{vmatrix} t = -x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}'),
(16,'-\frac{1}{2} \int e^t dt'),
(16,'-\frac{1}{3} t^{\frac{3}{2}} + c'),
(16,'\begin{vmatrix} u = x   &  \frac{dv}{dx} = e^{-x} \\ \frac{du}{dx} = 1   &  v = -e^{-x}\end{vmatrix}'),
(16,'-xe^{-x} + \int e^{-x}dx'),
(17,'-\frac{1}{2} \int e^t dt'),
(17,'-\frac{1}{2}e^t + c'),
(17,'-\frac{1}{2}e^{-x^2} + c'),
(17,'-lnt + c'),
(17,'-ln(cosx) + c'),
(18,'\frac{1}{8}x + \frac{1}{32}sin4x + c'),
(18,'\begin{vmatrix} u = t & \frac{dv}{dt} = e^t\\  \frac{du}{dt} = 1 & v = e^t\end{vmatrix}'),
(18,'xsin(lnx) - xcos(lnx) - \int sin(lnx)dx'),
(18,'\frac{1}{tlnt}dt'),
(18,'lnu + c'),
(19,'lnu + c'),
(19,'\begin{vmatrix} t = e^x \\  dt = e^xdx \end{vmatrix}'),
(19,'xarcsinx - \int \frac{x}{\sqrt{1-x^2}}'),
(19,'xarcsinx + \sqrt{t} + c'),
(19,'xarcsinx + \sqrt{1-x^2} + c'),
(20,'\begin{vmatrix} u = cos(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = -\frac{1}{x} sin(lnx) & v = x \end{vmatrix}'),
(20,'\frac{1}{tlnt}dt'),
(20,'\int \frac{1}{u}du'),
(20,'xarcsinx - \int \frac{x}{\sqrt{1-x^2}}'),
(20,'\int \frac{1}{2}(1-cos2x)\cdot\frac{1}{2}(1+cos2x)dx'),
(21,'2\int te^t dt '),
(21,'\begin{vmatrix} u = sin(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = \frac{1}{x}cos(lnx) & v = x \end{vmatrix}'),
(21,'\begin{vmatrix} t = e^x \\  dt = e^xdx \end{vmatrix}'),
(21,'xarcsinx - \int \frac{x}{\sqrt{1-x^2}}'),
(21,'xarcsinx + \sqrt{t} + c'),
(22,'\begin{vmatrix} t = \sqrt{x}\\  dt = \frac{1}{2\sqrt{x}}dx\\ dx = 2tdt \end{vmatrix}'),
(22,'\begin{vmatrix} u = sin(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = \frac{1}{x}cos(lnx) & v = x \end{vmatrix}'),
(22,'lnu + c'),
(22,'arctgt + c'),
(22,'\begin{vmatrix} u = arcsinx & \frac{dv}{dt} = 1 \\  \frac{du}{dt} = \frac{1}{\sqrt{1 - x^2}} & v = x \end{vmatrix}'),
(23,'\sqrt{x}e^{\sqrt{x}} - e^{\sqrt{x}} + c'),
(23,'xsin(lnx) - xcos(lnx) - \int sin(lnx)dx'),
(23,'\frac{1}{2}x(sin(lnx) - cos(lnx)) + c'),
(23,'ln(ln(sinx)) + c'),
(23,'\begin{vmatrix} t = e^x \\  dt = e^xdx \end{vmatrix}');
