INSERT INTO ans_windows (id, answers, window_number)
VALUES
(0,'c',1),
(1,'ax + c',1),
(2,'\frac{x^{r+1}}{r+1} + c',1),
(3,'lnx + c',1),
(4,'\frac{a^x}{lna} + c',1),
(5,'e^x + c',1),
(6,'-cosx + c',1),
(7,'sinx + c',1),
(8,'tgx + c',1),
(9,'-ctgx + c',1),
(10,'arctgx + c',1),
(11,'arcsinx + c',1),
(12,'\begin{vmatrix} t = -x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}',1),
(12,'-\frac{1}{2} \int e^t dt',2),
(12,'-\frac{1}{2}e^t + c',3),
(12,'-\frac{1}{2}e^{-x^2} + c',4),
(13,'\begin{vmatrix} t = a^2-x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}',1),
(13,'-\frac{1}{2} \int \sqrt{t} dt',2),
(13,'-\frac{1}{3} t^{\frac{3}{2}} + c',3),
(13,'-\frac{1}{3} \sqrt{a^2 - x^2}^3',4),
(14,'\begin{vmatrix} u = x   &  \frac{dv}{dx} = e^{-x} \\ \frac{du}{dx} = 1   &  v = -e^{-x}\end{vmatrix}',1),
(14,'-xe^{-x} + \int e^{-x}dx',2),
(14,'-xe^{-x} - e^{-x} + c',3),
(15,'\int \frac{sinx}{cosx}dx',1),
(15,'\begin{vmatrix} t = cosx \\ dt = -sinxdx \end{vmatrix}',2),
(15,'-\int \frac{1}{t}dt',3),
(15,'-lnt + c',4),
(15,'-ln(cosx) + c',5),
(16,'\begin{vmatrix} t = lnx \\ dt = \frac{1}{x}dx  \end{vmatrix}',1),
(16,'\int \frac{1}{t}dt',2),
(16,'lnt + c',3),
(16,'ln(lnx) + c',4),
(17,'\begin{vmatrix} u = x   &  \frac{dv}{dx} = sinx \\ \frac{du}{dx} = 1  &   v = -cosx\end{vmatrix}',1),
(17,'-xcosx + \int cosxdx',2),
(17,'-xcosx + sinx + c',3),
(18,'\begin{vmatrix} t = \sqrt{x}\\  dt = \frac{1}{2\sqrt{x}}dx\\ dx = 2tdt \end{vmatrix}',1),
(18,'2\int te^t dt ',2),
(18,'\begin{vmatrix} u = t & \frac{dv}{dt} = e^t\\  \frac{du}{dt} = 1 & v = e^t\end{vmatrix}',3),
(18,'te^t - \int e^t',4),
(18,'te^t - e^t + c',5),
(18,'\sqrt{x}e^{\sqrt{x}} - e^{\sqrt{x}} + c',6),
(19,'\begin{vmatrix} u = sin(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = \frac{1}{x}cos(lnx) & v = x \end{vmatrix}',1),
(19,'xsin(lnx) - \int cos(lnx)dx',2),
(19,'\begin{vmatrix} u = cos(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = -\frac{1}{x} sin(lnx) & v = x \end{vmatrix}',3),
(19,'xsin(lnx) - xcos(lnx) - \int sin(lnx)dx',4),
(19,'\frac{1}{2}x(sin(lnx) - cos(lnx)) + c',5),
(20,'\int \frac{cosx}{ln(sinx)sinx}dx ',1),
(20,'\begin{vmatrix} t = sinx \\ dt = cosxdx  \end{vmatrix}',2),
(20,'\frac{1}{tlnt}dt',3),
(20,'\begin{vmatrix} u = lnt \\ du = \frac{1}{t}dt \end{vmatrix}',4),
(20,'\int \frac{1}{u}du',5),
(20,'lnu + c',6),
(20,'ln(ln(sinx)) + c',7),
(21,'\int \frac{e^x}{e^{2x}+1}dx',1),
(21,'\begin{vmatrix} t = e^x \\  dt = e^xdx \end{vmatrix}',2),
(21,'\frac{1}{t^2 + 1}dt',3),
(21,'arctgt + c',4),
(21,'arctg(e^x) + c',5),
(22,'\begin{vmatrix} u = arcsinx & \frac{dv}{dt} = 1 \\  \frac{du}{dt} = \frac{1}{\sqrt{1 - x^2}} & v = x \end{vmatrix}',1),
(22,'xarcsinx - \int \frac{x}{\sqrt{1-x^2}}',2),
(22,'\begin{vmatrix} t = 1 - x^2 \\ dt = -2xdx \\ -\frac{1}{2}dt = xdx \end{vmatrix}',3),
(22,'xarcsinx + \int \frac{1}{2\sqrt{t}}dt',4),
(22,'xarcsinx + \sqrt{t} + c',5),
(22,'xarcsinx + \sqrt{1-x^2} + c',6),
(23,'\int \frac{1}{2}(1-cos2x)\cdot\frac{1}{2}(1+cos2x)dx',1),
(23,'\frac{1}{4}(1 - cos^2 2x)dx',2),
(23,'\frac{1}{4} \int sin^2 2xdx ',3),
(23,'\frac{1}{8} \int (1 - cos4x)dx ',4),
(23,'\frac{1}{8}x + \frac{1}{32}sin4x + c',5);
