INSERT INTO user_windows (id, proposed_answers)
VALUES
(0,'1'),
(0,'x + c'),
(0,'x'),
(1,'ax'),
(1,'a'),
(1,'a + c'),
(2,'x^{r+1} + c'),
(2,'x^r + c'),
(2,'\frac{x^{r+1}}{r} + c'),
(3,'c'),
(3,'x + c'),
(3,'\frac{-1}{x} + c'),
(4,'a^x + c'),
(4,'a^x lna + c'),
(4,'a^{x+1} + c'),
(5,'e^{x+1} + c'),
(5,'cosx'),
(5,'sinx'),
(6,'cosx + c'),
(6,'\frac{1}{sinx} + c'),
(6,'\frac{1}{cosx} + c'),
(7,'-sinx + c'),
(7,'cos^{-1}x'),
(7,'arcsinx'),
(8,'ctgx + c'),
(8,'\frac{1}{cosx} + c'),
(8,'\frac{1}{sinx} + c'),
(9,'-tgx + c'),
(9,'\frac{1}{sinx} + c'),
(9,'arcsinx'),
(10,'ln(x^2+1) + c'),
(10,'\frac{1}{x+1} + c'),
(10,'\frac{ln(x^2+1)}{x} + c'),
(11,'arccosx + c'),
(11,'arctgx + c'),
(11,'arcctgx + c'),
(12,'\begin{vmatrix} t = -x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}'),
(12,'\begin{vmatrix} t = cosx \\ dt = -sinxdx \end{vmatrix}'),
(12,'-lnt + c'),
(12,'\int \frac{1}{t}dt'),
(12,'-xcosx + sinx + c'),
(13,'-\frac{1}{2} \int e^t dt'),
(13,'-\frac{1}{2} \int \sqrt{t} dt'),
(13,'-xe^{-x} + \int e^{-x}dx'),
(13,'ln(lnx) + c'),
(13,'-xcosx + \int cosxdx'),
(14,'-\frac{1}{2}e^t + c'),
(14,'-xe^{-x} - e^{-x} + c'),
(14,'-\int \frac{1}{t}dt'),
(14,'lnt + c'),
(14,'-xcosx + \int cosxdx'),
(15,'-\frac{1}{2}e^t + c'),
(15,'-\frac{1}{2}e^{-x^2} + c'),
(15,'-\frac{1}{3} t^{\frac{3}{2}} + c'),
(15,'-\frac{1}{3} \sqrt{a^2 - x^2}^3'),
(15,'\int \frac{sinx}{cosx}dx'),
(16,'-\frac{1}{2}e^{-x^2} + c'),
(16,'-\frac{1}{2} \int \sqrt{t} dt'),
(16,'-\frac{1}{3} \sqrt{a^2 - x^2}^3'),
(16,'-ln(cosx) + c'),
(16,'-xcosx + \int cosxdx'),
(17,'\begin{vmatrix} t = -x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}'),
(17,'-ln(cosx) + c'),
(17,'\int \frac{1}{t}dt'),
(17,'lnt + c'),
(17,'-xcosx + sinx + c'),
(18,'\begin{vmatrix} u = t & \frac{dv}{dt} = e^t\\  \frac{du}{dt} = 1 & v = e^t\end{vmatrix}'),
(18,'\begin{vmatrix} u = sin(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = \frac{1}{x}cos(lnx) & v = x \end{vmatrix}'),
(18,'\begin{vmatrix} u = cos(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = -\frac{1}{x} sin(lnx) & v = x \end{vmatrix}'),
(18,'xsin(lnx) - xcos(lnx) - \int sin(lnx)dx'),
(18,'\frac{1}{tlnt}dt'),
(19,'\frac{1}{8}x + \frac{1}{32}sin4x + c'),
(19,'\begin{vmatrix} u = t & \frac{dv}{dt} = e^t\\  \frac{du}{dt} = 1 & v = e^t\end{vmatrix}'),
(19,'xsin(lnx) - \int cos(lnx)dx'),
(19,'\int \frac{1}{u}du'),
(19,'\frac{1}{t^2 + 1}dt'),
(20,'\frac{1}{8} \int (1 - cos4x)dx '),
(20,'\begin{vmatrix} u = t & \frac{dv}{dt} = e^t\\  \frac{du}{dt} = 1 & v = e^t\end{vmatrix}'),
(20,'te^t - \int e^t'),
(20,'\begin{vmatrix} u = lnt \\ du = \frac{1}{t}dt \end{vmatrix}'),
(20,'\int \frac{e^x}{e^{2x}+1}dx'),
(21,'te^t - e^t + c'),
(21,'\begin{vmatrix} u = cos(lnx) & \frac{dv}{dt} = 1\\  \frac{du}{dt} = -\frac{1}{x} sin(lnx) & v = x \end{vmatrix}'),
(21,'\int \frac{cosx}{ln(sinx)sinx}dx '),
(21,'\int \frac{1}{u}du'),
(21,'lnu + c'),
(22,'\begin{vmatrix} t = \sqrt{x}\\  dt = \frac{1}{2\sqrt{x}}dx\\ dx = 2tdt \end{vmatrix}'),
(22,'\int \frac{cosx}{ln(sinx)sinx}dx '),
(22,'\begin{vmatrix} t = 1 - x^2 \\ dt = -2xdx \\ -\frac{1}{2}dt = xdx \end{vmatrix}'),
(22,'xarcsinx + \int \frac{1}{2\sqrt{t}}dt'),
(22,'xarcsinx + \sqrt{1-x^2} + c'),
(23,'2\int te^t dt '),
(23,'\frac{1}{tlnt}dt'),
(23,'\int \frac{1}{u}du'),
(23,'ln(ln(sinx)) + c'),
(23,'\begin{vmatrix} t = 1 - x^2 \\ dt = -2xdx \\ -\frac{1}{2}dt = xdx \end{vmatrix}');
