INSERT INTO ans_windows (id, answers, window_number)
VALUES
(0,'c',1),
(1,'ax + c',1),
(2,'\frac{x^{r+1}}{r+1} + c',1),
(3,'lnx + c',1),
(4,'\frac{a^x}{lna} + c',1),
(5,'e^x + c',1),
(6,'-cosx + c',1),
(7,'sinx + c',1),
(8,'tgx + c',1),
(9,'-ctgx + c',1),
(10,'arctgx + c',1),
(11,'arcsinx + c',1),
(11,'\begin{vmatrix} t = -x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}',1),
(11,'-\frac{1}{2} \int e^t dt',2),
(11,'-\frac{1}{2}e^t + c',3),
(11,'-\frac{1}{2}e^{-x^2} + c',4),
(12,'\begin{vmatrix} t = a^2-x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}',1),
(12,'-\frac{1}{2} \int \sqrt{t} dt',2),
(12,'-\frac{1}{3} t^{\frac{3}{2}} + c',3),
(12,'-\frac{1}{3} \sqrt{a^2 - x^2}^3',4),
(13,'\begin{vmatrix} u = x     v' = e^{-x} \\ u' = 1     v = -e^{-x}\end{vmatrix}',1),
(13,'-xe^{-x} + \int e^{-x}dx',2),
(13,'-xe^{-x} - e^{-x} + c',3),
(14,'\int \frac{sinx}{cosx}dx',1),
(14,'\begin{vmatrix} t = cosx \\ dt = -sinxdx \end{vmatrix}',2),
(14,'-\int \frac{1}{t}dt',3),
(14,'-lnt + c',4),
(14,'-ln(cosx) + c',5),
(15,'\begin{vmatrix} t = lnx \\ dt = \frac{1}{x}dx  \end{vmatrix}',1),
(15,'\int \frac{1}{t}dt',2),
(15,'lnt + c',3),
(15,'ln(lnx) + c',4),
(16,'\begin{vmatrix} u = x     v' = sinx \\ u' = 1     v = -cosx\end{vmatrix}',1),
(16,'-xcosx + \int cosxdx',2),
(16,'-xcosx + sinx + c',3);
