INSERT INTO user_windows (id, proposed_answers)
VALUES
(1,'c'),
(1,'1'),
(1,'x + c'),
(1,'x'),
(2,'ax + c'),
(2,'ax'),
(2,'a'),
(2,'a + c'),
(3,'x^{r+1} + c'),
(3,'x^r + c'),
(3,'\frac{x^{r+1}}{r+1} + c'),
(3,'\frac{x^{r+1}}{r} + c'),
(4,'lnx + c'),
(4,'c'),
(4,'x + c'),
(4,'\frac{-1}{x} + c'),
(5,'\frac{a^x}{lna} + c'),
(5,'a^x + c'),
(5,'a^x lna + c'),
(5,'a^{x+1} + c'),
(6,'e^x + c'),
(6,'e^{x+1} + c'),
(6,'cosx'),
(6,'sinx'),
(7,'cosx + c'),
(7,'-cosx + c'),
(7,'\frac{1}{sinx} + c'),
(7,'\frac{1}{cosx} + c'),
(8,'-sinx + c'),
(8,'sinx + c'),
(8,'cos^{-1}x'),
(8,'arcsinx'),
(9,'tgx + c'),
(9,'ctgx + c'),
(9,'\frac{1}{cosx} + c'),
(9,'\frac{1}{sinx} + c'),
(10,'-ctgx + c'),
(10,'-tgx + c'),
(10,'\frac{1}{sinx} + c'),
(10,'arcsinx'),
(11,'arctgx + c'),
(11,'ln(x^2+1) + c'),
(11,'\frac{1}{x+1} + c'),
(11,'\frac{ln(x^2+1)}{x} + c'),
(12,'arcsinx + c'),
(12,'arccosx + c'),
(12,'arctgx + c'),
(12,'arcctgx + c');
