INSERT INTO user_windows (id, proposed_answers)
VALUES
(0,'1'),
(0,'x + c'),
(0,'x'),
(1,'ax'),
(1,'a'),
(1,'a + c'),
(2,'x^{r+1} + c'),
(2,'x^r + c'),
(2,'\frac{x^{r+1}}{r} + c'),
(3,'c'),
(3,'x + c'),
(3,'\frac{-1}{x} + c'),
(4,'a^x + c'),
(4,'a^x lna + c'),
(4,'a^{x+1} + c'),
(5,'e^{x+1} + c'),
(5,'cosx'),
(5,'sinx'),
(6,'cosx + c'),
(6,'\frac{1}{sinx} + c'),
(6,'\frac{1}{cosx} + c'),
(7,'-sinx + c'),
(7,'cos^{-1}x'),
(7,'arcsinx'),
(8,'ctgx + c'),
(8,'\frac{1}{cosx} + c'),
(8,'\frac{1}{sinx} + c'),
(9,'-tgx + c'),
(9,'\frac{1}{sinx} + c'),
(9,'arcsinx'),
(10,'ln(x^2+1) + c'),
(10,'\frac{1}{x+1} + c'),
(10,'\frac{ln(x^2+1)}{x} + c'),
(11,'arccosx + c'),
(11,'arctgx + c'),
(11,'arcctgx + c'),
(12,'-\frac{1}{2}e^t + c'),
(12,'-\frac{1}{3} t^{\frac{3}{2}} + c'),
(12,'\int \frac{1}{t}dt'),
(12,'-xe^{-x} - e^{-x} + c'),
(12,'\begin{vmatrix} t = lnx \\ dt = \frac{1}{x}dx  \end{vmatrix}'),
(13,'ln(lnx) + c'),
(13,'\begin{vmatrix} t = a^2-x^2\\  dt = -2xdx\\ xdx = -\frac{dt}{2} \end{vmatrix}'),
(13,'\begin{vmatrix} u = x     \frac{dv}{dx} = sinx \\ \frac{du}{dx} = 1     v = -cosx\end{vmatrix}'),
(13,'-xe^{-x} + \int e^{-x}dx'),
(13,'-xcosx + sinx + c'),
(14,'-\frac{1}{2}e^{-x^2} + c'),
(14,'-\frac{1}{3} \sqrt{a^2 - x^2}^3'),
(14,'\begin{vmatrix} u = x     \frac{dv}{dx} = sinx \\ \frac{du}{dx} = 1     v = -cosx\end{vmatrix}'),
(14,'-xcosx + sinx + c'),
(14,'\int \frac{sinx}{cosx}dx'),
(15,'-\frac{1}{3} t^{\frac{3}{2}} + c'),
(15,'\begin{vmatrix} t = cosx \\ dt = -sinxdx \end{vmatrix}'),
(15,'-\frac{1}{2}e^t + c'),
(15,'-\int \frac{1}{t}dt'),
(15,'-\frac{1}{2} \int e^t dt'),
(16,'-\frac{1}{2}e^t + c'),
(16,'-ln(cosx) + c'),
(16,'-\frac{1}{3} \sqrt{a^2 - x^2}^3'),
(16,'-lnt + c'),
(16,'-xcosx + \int cosxdx'),
(17,'-lnt + c'),
(17,'-\frac{1}{3} t^{\frac{3}{2}} + c'),
(17,'ln(lnx) + c');
